//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCGridDemo.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Index { get; set; }
        public Nullable<int> Position { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Imprint { get; set; }
        public string PublisherGroup { get; set; }
        public Nullable<long> Volume { get; set; }
        public string Value { get; set; }
        public string RRP { get; set; }
        public string ASP { get; set; }
        public Nullable<int> BindingTypeId { get; set; }
        public Nullable<System.DateTime> PublDate { get; set; }
        public string ProductClass { get; set; }
    
        public virtual BindingType BindingType { get; set; }
    }
}
